services:

  mysql:
    image: mysql:8.0.32
    container_name: alexandriadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alexandriadb